name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        # Use clean install to work around dependency issues on Linux
        run: |
          rm -rf node_modules bun.lock
          bun install

      - name: TypeScript Check
        run: bun run typecheck

      - name: Prettier Check
        run: bun run lint:format

      - name: MDX Validation
        run: bun run lint:mdx

      - name: Build
        run: bun run build
        env:
          CI: "true"
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"

      - name: Run Tests
        run: bun test
